---
title: "Untitled"
date: "MM/DD/YYYY"
output:
  html_document:
    toc: true
    toc_float: true
    df_print: paged

#adapted from https://github.com/associatedpress/apstyle/blob/master/R/rmd_render.R     #using method from https://stackoverflow.com/questions/26174565/r-in-rstudio-how-do-i-make-knitr-output-to-a-different-folder-to-avoid-clutteri
#make sure Tools -> Global Options -> R Markdown -> Evaluate chunks in directory is set to "project"
knit: (function(inputFile, encoding) {rmarkdown::render(inputFile, encoding = encoding, knit_root_dir = rprojroot::find_rstudio_root_file(), output_dir = "docs")})
---
<!-- Timestamp: leave this in to automatically track when a file is rendered -->
*Rendered at `r format(Sys.time(), '%I:%M %p, %b. %d, %Y')`*

<!-- Contact info: leave author/reporter/editor contact info here -->
*Firstname Lastname (<email@domain.com>)*

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
  message = FALSE,
  warning = FALSE
  )

knitr::opts_knit$set(
  root.dir = rprojroot::find_rstudio_root_file()
  )
```
```{r initialize}
#devtools::install_github("associatedpress/apstyle")
library(apstyle) #AP ggplot theme can be applied to a ggplot object via + theme_ap()


# Load files, environment variables, libraries, etc. here
library(tidyverse)


```

<!-- Project structure adapted from https://github.com/associatedpress/cookiecutter-r-project. To use on your computer follow these instructions: https://datakit.ap.org/  -->

## Story Pitch

<!-- This section is for writing your three-ish paragraph story pitch. -->


## Data Interview
<!-- This section is for the final clean transcript of your data interview. -->

### Question:
```{r}

```
<!-- If the output of the chunk doesn't obviously answer your question, summarize your finding in a brief sentence here. -->


## References

<!-- This section is for including references to related material -->

- CREDO National Charter School Study 2013: http://credo.stanford.edu/documents/NCSS%202013%20Final%20Draft.pdf

- NBER Working Paper No. 23947: The Labor Market Effects of Offshoring by U.S. Multinational Firms: Evidence from Changes in Global Tax Policies: http://www.nber.org/papers/w23947

<!-- This section is for a tests code block -->

```{r tests}
# Leave this block of code at the end of the file
# If a test fails it will stop the Rmd document from knitting
# Run tests like so:
# source("tests/etl_test.R")
```
